version: "3.9"
services:
  api:
    build:
      context: .
    image: ekaterinavvv/skypro_keitoekka_app
    ports:
      - 80:80
    depends_on:
      pg:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
        - ./docker_config.py:/code/default_config.py
  migrations:
    build:
      context: .
    image: ekaterinavvv/skypro_keitoekka_app
    depends_on:
      pg:
        condition: service_healthy
    command: flask db upgrade
    volumes:
      - ./docker_config.py:/code/default_config.py
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: flask_app
      POSTGRES_PASSWORD: flask_app_password
      POSTGRES_DB: flask_app
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./pg_data:/var/lib/postgresql/data
