name: Build and lesson_25 workflow
on: [ push ]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: docker build
        run: docker build -t ekaterinavvv/skypro_keitoekka_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: docker push
        run: docker push ekaterinavvv/skypro_keitoekka_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID
  lesson_25:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: render configs
        run: |
          mkdir lesson_25
          cat docker-compose-ci.yaml | envsubst > lesson_25/docker-compose.yaml
          cat docker_ci_config.py | envsubst > lesson_25/docker_config.py
      - name: clone files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "lesson_25/docker-compose.yaml,lesson_25/docker_config.py"
          target: "flask_app_ci"
          strip_components: 1
      - name: run lesson_25
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd flask_app_ci
            echo ${{ secrets.PASSWORD }} | sudo -S docker-compose up -d
            
            

          

